services:
  # PostgreSQL + TimescaleDB
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: demo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 240203
      POSTGRES_DB: university_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lakehouse-network

  # Kafka
  kafka:
    image: apache/kafka:4.1.1
    container_name: demo-kafka
    hostname: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: CONTROLLER://:29093,PLAINTEXT://:19092,PLAINTEXT_HOST://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: 4L6g3nShT-eMCtK--X86sw
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    ports:
      - "9094:9094"
    networks:
      - lakehouse-network

  # MinIO
  minio:
    image: minio/minio:latest
    container_name: demo-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - lakehouse-network

  # Khởi tạo bucket
  minio-init:
    image: minio/mc:latest
    container_name: demo-minio-init
    depends_on:
      - minio
    networks:
      - lakehouse-network
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin); do
        echo 'Waiting for MinIO...';
        sleep 2;
      done;
      if ! /usr/bin/mc ls myminio/university-lakehouse > /dev/null 2>&1; then
        /usr/bin/mc mb myminio/university-lakehouse;
        echo 'Bucket initialized';
      else
        echo 'Bucket already exists';
      fi;
      exit 0;
      "

  # Trino
  trino:
    image: trinodb/trino:435
    container_name: demo-trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/catalog:/etc/trino/catalog
    depends_on:
      - minio
    networks:
      - lakehouse-network


# Thêm Project Nessie (Iceberg Catalog)
  nessie:
    image: projectnessie/nessie:latest
    container_name: demo-nessie
    ports:
      - "19120:19120" # Cổng giao tiếp API của Nessie
    environment:
      # Nessie hỗ trợ lưu siêu dữ liệu trên In-memory hoặc RocksDB (nhẹ nhàng cho sinh viên)
      - QUARKUS_PROFILE=prod
      - NESSIE_VERSION_STORE_TYPE=IN_MEMORY
    networks:
      - lakehouse-network


  # Apache Superset
  superset:
    image: apache/superset:3.1.0
    container_name: demo-superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: university_lakehouse_secret_key
    user: "root"
    volumes:
      - superset_home:/app/superset_home
      - ./superset_config.py:/app/pythonpath/superset_config.py
    command: >
      sh -c "
      superset db upgrade &&
      superset fab create-admin
      --username admin
      --firstname Admin
      --lastname User
      --email admin@fab.org
      --password admin &&
      superset init &&
      /usr/bin/run-server.sh
      "
    depends_on:
      - trino
    networks:
      - lakehouse-network

volumes:
  postgres_data:
  minio_data:
  superset_home:

networks:
  lakehouse-network:
    driver: bridge